#!/usr/bin/env bash

BASE_LINK="https://upload.wikimedia.org/wikipedia/commons/"
B_L="${BASE_LINK}8/81/Chess_bdt60.png"
B_D="${BASE_LINK}9/9b/Chess_blt60.png"
K_L="${BASE_LINK}e/e3/Chess_kdt60.png"
K_D="${BASE_LINK}3/3b/Chess_klt60.png"
N_L="${BASE_LINK}f/f1/Chess_ndt60.png"
N_D="${BASE_LINK}2/28/Chess_nlt60.png"
P_L="${BASE_LINK}c/cd/Chess_pdt60.png"
P_D="${BASE_LINK}0/04/Chess_plt60.png"
Q_L="${BASE_LINK}a/af/Chess_qdt60.png"
Q_D="${BASE_LINK}4/49/Chess_qlt60.png"
R_L="${BASE_LINK}a/a0/Chess_rdt60.png"
R_D="${BASE_LINK}5/5c/Chess_rlt60.png"

wget "$B_L"
wget "$B_D"
wget "$K_L"
wget "$K_D"
wget "$N_L"
wget "$N_D"
wget "$P_L"
wget "$P_D"
wget "$Q_L"
wget "$Q_D"
wget "$R_L"
wget "$R_D"
